# Using base image of PHP-7 installed on "apache htttd"
# This base image is derived from "Ubuntu"
FROM php:7.0-apache

# copy contents of local directory "files" into 
# deployment directory in container
COPY files /var/www/html/

